// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/account" | "/pricing" | "/privacy" | "/scorebar-preview" | "/season/[id]" | "/season/[id]/team/[teamId]" | "/share/[slug]" | "/terms" | "/unsubscribe/[token]" | "/welcome"
type AppRouteHandlerRoutes = "/api/account" | "/api/account/free-season" | "/api/billing/checkout" | "/api/billing/portal" | "/api/entitlements" | "/api/image-proxy" | "/api/import/commit" | "/api/import/espn" | "/api/import/screenshot" | "/api/import/sleeper" | "/api/nfl-weeks" | "/api/notifications/send" | "/api/notifications/subscribe" | "/api/platform/connections" | "/api/platform/history" | "/api/platform/sync/scores" | "/api/publish" | "/api/saved-leagues" | "/api/seasons" | "/api/seasons/[id]" | "/api/seasons/[id]/revisions" | "/api/stripe/webhook" | "/auth/callback"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/account": {}
  "/api/account": {}
  "/api/account/free-season": {}
  "/api/billing/checkout": {}
  "/api/billing/portal": {}
  "/api/entitlements": {}
  "/api/image-proxy": {}
  "/api/import/commit": {}
  "/api/import/espn": {}
  "/api/import/screenshot": {}
  "/api/import/sleeper": {}
  "/api/nfl-weeks": {}
  "/api/notifications/send": {}
  "/api/notifications/subscribe": {}
  "/api/platform/connections": {}
  "/api/platform/history": {}
  "/api/platform/sync/scores": {}
  "/api/publish": {}
  "/api/saved-leagues": {}
  "/api/seasons": {}
  "/api/seasons/[id]": { "id": string; }
  "/api/seasons/[id]/revisions": { "id": string; }
  "/api/stripe/webhook": {}
  "/auth/callback": {}
  "/pricing": {}
  "/privacy": {}
  "/scorebar-preview": {}
  "/season/[id]": { "id": string; }
  "/season/[id]/team/[teamId]": { "id": string; "teamId": string; }
  "/share/[slug]": { "slug": string; }
  "/terms": {}
  "/unsubscribe/[token]": { "token": string; }
  "/welcome": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
