// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/account">> = Specific
  const handler = {} as typeof import("../../../app/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../../app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../../app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/scorebar-preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/scorebar-preview">> = Specific
  const handler = {} as typeof import("../../../app/scorebar-preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/season/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/season/[id]">> = Specific
  const handler = {} as typeof import("../../../app/season/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/season/[id]/team/[teamId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/season/[id]/team/[teamId]">> = Specific
  const handler = {} as typeof import("../../../app/season/[id]/team/[teamId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/share/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/share/[slug]">> = Specific
  const handler = {} as typeof import("../../../app/share/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/unsubscribe/[token]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unsubscribe/[token]">> = Specific
  const handler = {} as typeof import("../../../app/unsubscribe/[token]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/welcome/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/welcome">> = Specific
  const handler = {} as typeof import("../../../app/welcome/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/account/free-season/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account/free-season">> = Specific
  const handler = {} as typeof import("../../../app/api/account/free-season/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/account">> = Specific
  const handler = {} as typeof import("../../../app/api/account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/billing/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/checkout">> = Specific
  const handler = {} as typeof import("../../../app/api/billing/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/billing/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/billing/portal">> = Specific
  const handler = {} as typeof import("../../../app/api/billing/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/entitlements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/entitlements">> = Specific
  const handler = {} as typeof import("../../../app/api/entitlements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/image-proxy/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/image-proxy">> = Specific
  const handler = {} as typeof import("../../../app/api/image-proxy/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/import/commit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/commit">> = Specific
  const handler = {} as typeof import("../../../app/api/import/commit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/import/espn/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/espn">> = Specific
  const handler = {} as typeof import("../../../app/api/import/espn/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/import/screenshot/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/screenshot">> = Specific
  const handler = {} as typeof import("../../../app/api/import/screenshot/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/import/sleeper/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/import/sleeper">> = Specific
  const handler = {} as typeof import("../../../app/api/import/sleeper/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/nfl-weeks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/nfl-weeks">> = Specific
  const handler = {} as typeof import("../../../app/api/nfl-weeks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/notifications/send/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/send">> = Specific
  const handler = {} as typeof import("../../../app/api/notifications/send/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/notifications/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/subscribe">> = Specific
  const handler = {} as typeof import("../../../app/api/notifications/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/platform/connections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform/connections">> = Specific
  const handler = {} as typeof import("../../../app/api/platform/connections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/platform/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform/history">> = Specific
  const handler = {} as typeof import("../../../app/api/platform/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/platform/sync/scores/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/platform/sync/scores">> = Specific
  const handler = {} as typeof import("../../../app/api/platform/sync/scores/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/publish">> = Specific
  const handler = {} as typeof import("../../../app/api/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/saved-leagues/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/saved-leagues">> = Specific
  const handler = {} as typeof import("../../../app/api/saved-leagues/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/seasons/[id]/revisions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seasons/[id]/revisions">> = Specific
  const handler = {} as typeof import("../../../app/api/seasons/[id]/revisions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/seasons/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seasons/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/seasons/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/seasons/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/seasons">> = Specific
  const handler = {} as typeof import("../../../app/api/seasons/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/stripe/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/stripe/webhook">> = Specific
  const handler = {} as typeof import("../../../app/api/stripe/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
