import fontkit from "@pdf-lib/fontkit";
import { PDFDocument, rgb } from "pdf-lib";
import type { GeneratedSchedule } from "./types";
import { teamDisplayName } from "./teamIdentity";

function hexToRgb(hex: string) {
  const value = hex.replace("#", "");
  return rgb(
    parseInt(value.slice(0, 2), 16) / 255,
    parseInt(value.slice(2, 4), 16) / 255,
    parseInt(value.slice(4, 6), 16) / 255,
  );
}

export async function downloadSchedulePdf(schedule: GeneratedSchedule) {
  const [archivoBytes, barlowBytes] = await Promise.all([
    fetch("/fonts/Archivo-Variable.ttf").then((response) => response.arrayBuffer()),
    fetch("/fonts/BarlowCondensed-Bold.ttf").then((response) => response.arrayBuffer()),
  ]);
  const pdfDocument = await PDFDocument.create();
  pdfDocument.registerFontkit(fontkit);
  const bodyFont = await pdfDocument.embedFont(archivoBytes, { subset: true });
  const displayFont = await pdfDocument.embedFont(barlowBytes, { subset: true });
  const green = hexToRgb("#117A45");
  const ink = hexToRgb("#15231C");
  const gray = hexToRgb("#607069");
  const line = hexToRgb("#D8E0DC");
  const gold = hexToRgb("#E3B940");
  const teamById = new Map(schedule.setup.teams.map((team) => [team.id, team]));
  const display = schedule.setup.display ?? { cityNames: true, managers: true, venues: true };

  let page = pdfDocument.addPage([612, 792]);
  let y = 734;
  const drawHeader = () => {
    page.drawRectangle({ x: 0, y: 752, width: 612, height: 40, color: ink });
    page.drawRectangle({ x: 44, y: 764, width: 16, height: 16, color: green });
    page.drawText("LEAGUE WEAVER", { x: 69, y: 765, font: displayFont, size: 15, color: rgb(1, 1, 1) });
    page.drawText(`${schedule.setup.name} · ${schedule.setup.seasonYear}`, { x: 568 - bodyFont.widthOfTextAtSize(`${schedule.setup.name} · ${schedule.setup.seasonYear}`, 8), y: 767, font: bodyFont, size: 8, color: rgb(0.84, 0.9, 0.87) });
  };
  drawHeader();
  page.drawText(schedule.setup.name, { x: 44, y, font: displayFont, size: 28, color: ink });
  y -= 21;
  page.drawText(`${schedule.setup.teams.length} teams · ${schedule.setup.weeks} weeks · Fairness score ${schedule.fairness.score}`, { x: 44, y, font: bodyFont, size: 9, color: gray });
  y -= 28;

  for (const week of schedule.weeks) {
    const blockHeight = 28 + week.games.length * 22;
    if (y - blockHeight < 42) {
      page = pdfDocument.addPage([612, 792]);
      drawHeader();
      y = 724;
    }
    page.drawRectangle({ x: 44, y: y - 3, width: 524, height: 22, color: rgb(0.95, 0.97, 0.96) });
    page.drawRectangle({ x: 44, y: y - 3, width: 4, height: 22, color: week.weekNumber === schedule.setup.weeks ? gold : green });
    page.drawText(`WEEK ${week.weekNumber}`, { x: 56, y: y + 3, font: displayFont, size: 12, color: ink });
    page.drawText(week.dateLabel, { x: 470, y: y + 4, font: bodyFont, size: 7, color: gray });
    y -= 19;
    for (const game of week.games) {
      const awayTeam = teamById.get(game.awayTeamId);
      const homeTeam = teamById.get(game.homeTeamId);
      const away = awayTeam ? teamDisplayName(awayTeam, display.cityNames) : game.awayTeamId;
      const home = homeTeam ? teamDisplayName(homeTeam, display.cityNames) : game.homeTeamId;
      page.drawText(away, { x: 56, y, font: bodyFont, size: 8, color: ink, maxWidth: 155 });
      page.drawText("at", { x: 221, y, font: bodyFont, size: 7, color: gray });
      page.drawText(home, { x: 242, y, font: bodyFont, size: 8, color: ink, maxWidth: 155 });
      if (display.venues) page.drawText(game.stadium, { x: 410, y, font: bodyFont, size: 7, color: gray, maxWidth: 148 });
      y -= 17;
      page.drawLine({ start: { x: 56, y: y + 8 }, end: { x: 568, y: y + 8 }, thickness: 0.5, color: line });
    }
    y -= 9;
  }

  const pages = pdfDocument.getPages();
  pages.forEach((pdfPage, index) => {
    pdfPage.drawText(`Generated by League Weaver · Page ${index + 1} of ${pages.length}`, { x: 44, y: 20, font: bodyFont, size: 7, color: gray });
  });
  const bytes = await pdfDocument.save();
  const blob = new Blob([new Uint8Array(bytes).buffer], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${schedule.setup.abbreviation.toLowerCase()}-${schedule.setup.seasonYear}-schedule.pdf`;
  anchor.click();
  URL.revokeObjectURL(url);
}
